"""Constants for the data pull."""

OBJECT_TYPE_TWEET = "tweet"
TWITTER_URL = "https://twitter.com/"
OBJECT_TYPE_FACEBOOK_POST = "facebook_post"
OBJECT_TYPE_FACEBOOK_COMMENT = "facebook_comment"
OBJECT_TYPE_YOUTUBE_VIDEO = "youtube_video"
OBJECT_TYPE_YOUTUBE_COMMENT = "youtube_comment"
YOUTUBE_VIDEOS_URL = "https://www.youtube.com/watch?v="
YOUTUBE_CHANNEL_URL = "https://www.youtube.com/channel/"
