version: "3.7"
services:
  phoenix-dev:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    volumes:
      - type: bind
        source: .
        target: /src
        consistency: cached

