version: "3.7"
x-phoenix-bind:
  &default-bind
  type: bind
  source: ../
  target: /src
  consistency: cached

services:
  phoenix-dev:
    build:
      context: ../
      dockerfile: ./docker/dev.Dockerfile
    image: phoenix-undp
    volumes:
      - *default-bind
    # See .jupyter/jupyter_notebook_config.py for setting
    command: ["jupyter","lab"]
    environment:
      - JUPYTER_CONFIG_DIR=/src/.jupyter
      - CROWDTANGLE_API_TOKEN=${CROWDTANGLE_API_TOKEN}
      - CT_RATE_LIMIT_CALLS=${CT_RATE_LIMIT_CALLS}
      - CROWDTANGLE_SCRAPE_LIST_ID=${CROWDTANGLE_SCRAPE_LIST_ID}
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_OAUTH_ACCESS_TOKEN=${TWITTER_OAUTH_ACCESS_TOKEN}
      - TWITTER_OAUTH_ACCESS_SECRET=${TWITTER_OAUTH_ACCESS_SECRET}
      - TWITTER_APPLICATION_KEY=${TWITTER_APPLICATION_KEY}
      - TWITTER_APPLICATION_SECRET=${TWITTER_APPLICATION_SECRET}
      - PRODUCTION_ARTIFACTS_URL_PREFIX=${PRODUCTION_ARTIFACTS_URL_PREFIX}
      - PRODUCTION_DASHBOARD_URL_PREFIX=${PRODUCTION_DASHBOARD_URL_PREFIX}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DASK_CLUSTER_IP=tcp://scheduler:8786
    ports:
      - "8888"

  dask-scheduler:
    image: phoenix-undp
    volumes:
      - *default-bind
    hostname: scheduler
    ports:
      - "8786"
      - "8787"
    command: ["dask-scheduler"]

  dask-worker:
    image: phoenix-undp
    volumes:
      - *default-bind
    command: ["dask-worker", "tcp://scheduler:8786"]
