version: "3.7"
x-phoenix-bind:
  &default-bind
  type: bind
  source: ../
  target: /src
  consistency: cached

services:
  phoenix-dev:
    build:
      context: ../
      dockerfile: ./docker/dev.Dockerfile
    image: phoenix-dev
    volumes:
      - *default-bind
    # See .jupyter/jupyter_notebook_config.py for setting
    command: ["jupyter","lab"]
    environment:
      - JUPYTER_CONFIG_DIR=/src/.jupyter
      - CROWDTANGLE_API_TOKEN=${CROWDTANGLE_API_TOKEN}
      - CT_RATE_LIMIT_CALLS=${CT_RATE_LIMIT_CALLS}
      - CROWDTANGLE_SCRAPE_LIST_ID=${CROWDTANGLE_SCRAPE_LIST_ID}
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_APPLICATION_TOKEN=${TWITTER_APPLICATION_TOKEN}
      - TWITTER_APPLICATION_SECRET=${TWITTER_APPLICATION_SECRET}
      - PRODUCTION_ARTIFACTS_URL_PREFIX=${PRODUCTION_ARTIFACTS_URL_PREFIX}
      - PRODUCTION_DASHBOARD_URL_PREFIX=${PRODUCTION_DASHBOARD_URL_PREFIX}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    ports:
      - "8888:8888"


