version: "3.7"
services:
  phoenix-dev:
    build:
      context: ../
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - type: bind
        source: ../
        target: /src
        consistency: cached
    # See .jupyter/jupyter_notebook_config.py for setting
    command: ["jupyter","lab"]
    environment:
      - JUPYTER_CONFIG_DIR=/src/.jupyter
      - CROWDTANGLE_API_TOKEN=${CROWDTANGLE_API_TOKEN}
    ports:
      - "8888:8888"


