"""Test Graphistry graph generating and plotting.

These tests require the following environmental variables to be set:
    - GRAPHISTRY_USERNAME
    - GRAPHISTRY_PASSWORD
These tests will (may) instantiate an actual Graphistry plot for the account specified in env vars.
"""
import pandas as pd
import pytest

from phoenix.tag.graphing import phoenix_graphistry


@pytest.mark.auth
def test_plot():
    """Test generating a real Graphistry plot for the account specified in env vars.

    This test also serves as a handy interface for creating Graphistry graphs with certain
    attributes or properties for testing I functionality.

    Use `pytest -s` to get the url print output for checking out the graph. Note that things like
    `urls_params` only appear in the URL it process and aren't hard backed into the plot.
    """
    edges = pd.DataFrame(
        {
            "source": [0, 0, 0, -1, -2],
            "destination": [1, 2, 3, -2, -1],
            "attribute_1": ["x", "y", "z", "foo", "baa"],
            "edge_weights": [0.1, 0.5, 1, 0, 0],
        }
    )
    nodes = pd.DataFrame(
        {
            "nodes": [0, 1, 2, 3, 4],
            "attribute_1": ["a", "ab", "ac", "d", "e"],
        }
    )
    plot_config = phoenix_graphistry.PlotConfig(
        "source",
        "destination",
        "nodes",
        "phoenix_integration_test_graph_name",
        "This graph was generated by an integration test and can be safely ignored/deleted.",
        edge_weight_col="edge_weights",
    )
    url = phoenix_graphistry.plot(edges, nodes, plot_config, "test_prefix")
    print(url)
    assert isinstance(url, str)
    assert url.startswith("https://hub.graphistry.com/graph/graph.html")
